# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95f658faee0edc4f3f3c6a56c8d89ece3eaea60924abd5b05f83e92528dc67cbf51aec21014ed8ad14f286867263c1d62c6b2c128999e5fc3e5de26e2b2d2fd9

test:
  secret_key_base: 6d1cde1914f0198ed0d527b173d8740151d7aff5bbe80deed36159251c47c29552a9475bedd29e4fed3026ab25c92bf4495fe12f567b0fb13f9cadcd9ed57140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
